name: 'Smart Contract Change Analyzer'
description: 'Analyzes changes in Solidity contracts between commits'
branding:
  icon: 'search'
  color: 'blue'
inputs:
  base_commit:
    description: 'Base commit SHA for comparison'
    required: true
  head_commit:
    description: 'Head commit SHA for comparison'
    required: true
  github_token:
    description: 'GitHub token for repository access'
    required: false
    default: ${{ github.token }}
  scopeignore_path:
    description: 'Path to .scopeignore file in repository (relative to repo root)'
    required: false
    default: '.scopeignore'
  api_token:
    description: 'API token for the audit service. Get it from https://savant.chat (Profile -> Settings -> API Keys)'
    required: false
  api_url:
    description: 'URL for the audit service API endpoint'
    required: false
    default: 'https://savant.chat/api/v1'
  dry_run:
    description: 'Whether to perform a dry run (do not create real audit)'
    required: false
    default: 'false'
  tier:
    description: 'Tier'
    required: false
    default: 'advanced'
  project_id:
    description: 'Documentation project ID'
    required: false
outputs:
  changes_file:
    description: 'Path to the JSON file with analyzed changes'
    value: 'changed_declarations.json'
  audit_response:
    description: 'Response from the audit service (if enabled)'
    value: ${{ steps.analyze.outputs.audit_response }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base_commit }}
    - ${{ inputs.head_commit }}
    - ${{ inputs.scopeignore_path }}
    - ${{ inputs.api_token }}
    - ${{ inputs.api_url }}
    - ${{ inputs.dry_run }}
    - ${{ inputs.tier }}
    - ${{ inputs.project_id }} 