name: 'Smart Contract Change Analyzer'
description: 'Analyzes changes in Solidity contracts between commits'
branding:
  icon: 'search'
  color: 'blue'
inputs:
  base_commit:
    description: 'Base commit SHA for comparison'
    required: true
  head_commit:
    description: 'Head commit SHA for comparison'
    required: true
  github_token:
    description: 'GitHub token for repository access'
    required: false
    default: ${{ github.token }}
  scopeignore_path:
    description: 'Path to .scopeignore file in repository (relative to repo root)'
    required: false
    default: '.scopeignore'
outputs:
  changes_file:
    description: 'Path to the JSON file with analyzed changes'
    value: 'changed_declarations.json'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base_commit }}
    - ${{ inputs.head_commit }} 