name: 'Solidity Change Analyzer'
description: 'Analyzes changes in Solidity contracts between commits'
branding:
  icon: 'search'
  color: 'blue'
inputs:
  base_commit:
    description: 'Base commit SHA for comparison'
    required: true
  head_commit:
    description: 'Head commit SHA for comparison'
    required: true
outputs:
  changes_file:
    description: 'Path to the JSON file with analyzed changes'
    value: 'changed_declarations.json'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base_commit }}
    - ${{ inputs.head_commit }} 