name: Smart Contract Change Analyzer
on:
  # Manual trigger with inputs
  workflow_dispatch:
    inputs:
      base_commit:
        description: 'Base commit SHA for comparison'
        required: true
      head_commit:
        description: 'Head commit SHA for comparison'
        required: true
        default: 'HEAD'
      send_to_audit:
        description: 'Send changes to audit service'
        required: false
        default: 'true'
        type: boolean

  # Automatically trigger on pull requests
  # pull_request:
  #   branches:
  #     - master
  #     - main

  # Trigger on push to specified branches
  # push:
  #   branches:
  #     - master
  #     - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Analyze Solidity Changes & Send to Savant Audit
        uses: samartsevigor/change-analyzer@v1.2.3
        with:
          # For manual trigger, use the provided inputs
          base_commit: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.base_commit || github.event_name == 'push' && github.event.before || github.event.pull_request.base.sha }}
          head_commit: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.head_commit || github.event_name == 'push' && github.sha || github.event.pull_request.head.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          scopeignore_path: '.scopeignore'  # Optional, defaults to '.scopeignore'
          api_token: ${{ secrets.SAVANT_API_TOKEN }}  # API token for the audit service
          api_url: 'https://savant.chat/api/v1/requests/create'
          send_to_audit: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.send_to_audit || 'true' }}
      
      - name: Upload Analysis Results
        uses: actions/upload-artifact@v4
        with:
          name: changed-declarations
          path: changed_declarations.json 